import nltk
from nltk.corpus import stopwords
import re
import emoji
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')


def removing_shortcuts(text):
    full_words = []
    shortcuts = {'u': 'you', 'y': 'why', 'r': 'are', 'doin': 'doing', 'hw': 'how', 'k': 'okay', 'm': 'am',
                 'b4': 'before',
                 'idc': "i do not care", 'ty': 'thank you', 'wlcm': 'welcome', 'bc': 'because', '<3': 'love',
                 'xoxo': 'love',
                 'ttyl': 'talk to you later', 'gr8': 'great', 'bday': 'birthday', 'awsm': 'awesome', 'gud': 'good',
                 'h8': 'hate',
                 'lv': 'love', 'dm': 'direct message', 'rt': 'retweet', 'wtf': 'hate', 'idgaf': 'hate',
                 'irl': 'in real life', 'yolo': 'you only live once', "don't": "do not", 'g8': 'great',
                 "won't": "will not", 'tbh': 'to be honest', 'caj': 'casual', 'Ikr': 'I know, right?',
                 'omw': 'on my way',
                 'ofc': 'of course', 'Idc': "I don't care", 'Irl': 'In real life', 'tbf': 'To be fair',
                 'obvs': 'obviously', 'v': 'very', 'atm': 'at the moment',
                 'col': 'crying out loud', 'gbu': 'god bless you', 'gby': 'god bless you', 'gotcha': 'I got you',
                 'hehe': 'laughing', 'haha': 'laughing', 'hf': 'have fun',
                 'hry': 'hurry', 'hw': 'hardwork', 'idc': 'i don’t care', 'ikr': 'i know right', 'k': 'ok',
                 'lmao': 'laughing my ass off', 'lol': 'laughing out loud',
                 'n1': 'nice one', 'na': 'not available', 'qt': 'cutie', 'qtpi': 'cutie pie', 'rip': 'rest in peace',
                 'sry': 'sorry', 'tc': 'take care',
                 'thnks': 'thanks', 'thx': 'thanks', 'thnk': 'thanks', 'ttyl': 'talk to you later', 'txt': 'text',
                 'ugh': 'disgusted', 'w8': 'wait', "not sad": "happy"}

    for token in text:
        if token in shortcuts.keys():
            token = shortcuts[token]
        full_words.append(token)
    text = " ".join(full_words)
    return text


def removing_stopwords(text):
    stop_words = set(stopwords.words('english'))
    stop = [x.lower() for x in stop_words]
    return [word for word in text if not word in stopwords.words()]


def lemmatization(words_big):
    lemma = WordNetLemmatizer()
    stemmed_words = [lemma.lemmatize(word, 'v') for word in words_big]
    stemmed_words = [lemma.lemmatize(word, 'n') for word in stemmed_words]
    return " ".join(stemmed_words)


def removing_not(text):
    d = {'not sad': 'Happy', 'not bad': 'Happy', 'not boring': 'Happy', 'not wrong': 'Happy', 'not bored': 'Happy',
         'not jealous': 'Happy', 'not happy': 'Sad', 'not well': 'Sad', 'not suitable': 'Angry', 'not right': 'Angry',
         'not good': 'Sad', 'not excited': 'Angry', 'not funny ': 'Sad', 'not  kind': 'Sad', 'not proud': 'Angry',
         'not cool': 'Angry', 'not funny': 'Angry', 'not kind': 'Angry', 'not open': 'Angry', 'not safe': 'Fear',
         'not enough': 'Empty', 'not know': 'Sad', 'not knowing': 'Sad', 'not believe': 'Angry',
         'not believing': 'Angry',
         'not understand': 'Sad', 'not understanding': 'Sad', 'no doubt': 'Happy', 'not think': 'Sad',
         'not thinking': 'Sad',
         'not recognise': 'Sad', 'not recognising': 'Sad', 'not forget': 'Angry', 'not forgetting': 'Angry',
         'not remember': 'Sad',
         'not remembering': 'Sad', 'not imagine': 'Sad', 'not imagining': 'Sad', 'not mean': 'Sad',
         'not meaning': 'Sad',
         'not agree': 'Angry', 'not agreeing': 'Sad', 'not disagree': 'Happy', 'not disagreeing': 'Happy',
         'not deny': 'Sad',
         'not denying': 'Sad', 'not promise': 'Angry', 'not promising': 'Angry', 'not satisfy': 'Sad',
         'not satisfying': 'Sad',
         'not realise': 'Sad', 'not realising': 'Sad', 'not appear': 'Angry', 'not appearing': 'Angry',
         'not please': 'Sad', 'not pleasing': 'Sad', 'not impress': 'Sad', 'not impressing': 'Sad',
         'not surprise': 'Sad', 'not surprising': 'Sad', 'not concern': 'Sad', 'not concerning': 'Sad',
         'not have': 'Sad', 'not having': 'Sad',
         'not own': 'Sad', 'not owning': 'Sad', 'not possess': 'Sad', 'not possessing': 'Sad', 'not lack': 'Sad',
         'not lacking': 'Sad',
         'not consist': 'Sad', 'not consisting': 'Sad', 'not involve': 'Sad', 'not involving': 'Sad',
         'not include': 'Sad', 'not including': 'Sad', 'not contain': 'Sad',
         'not containing': 'Sad', 'not love': 'Sad', 'not like': 'Angry',
         'not hate': 'Happy', 'not hating': 'Happy', 'not adore': 'Sad', 'not adoring': 'Sad', 'not prefer': 'Sad',
         'not preferring': 'Sad', 'not care': 'Angry', 'not mind': 'Angry', 'not minding': 'Sad',
         'not want': 'Angry', 'not wanting': 'Sad',
         'not need': 'Angry', 'not needing': 'Angry', 'not desire': 'Sad', 'not desiring': 'Sad', 'not wish': 'Sad',
         'not wishing': 'Sad', 'not hope': 'Sad', 'not hoping': 'Sad', 'not appreciate': 'Sad',
         'not appreciating': 'Sad',
         'not value': 'Sad', 'not valuing': 'Sad', 'not owe': 'Sad', 'not owing': 'Sad', 'not seem': 'Sad',
         'not seeming': 'Sad', 'not fit': 'Sad', 'not fitting': 'Sad', 'not depend': 'Sad',
         'not depending': 'Sad', 'not matter': 'Sad', 'not afford': 'Sad', 'not affording': 'Sad', 'not aim': 'Sad',
         'not aiming': 'Sad', 'not attempt': 'Angry', 'not attempting': 'Angry', 'not ask': 'Angry',
         'not asking': 'Angry', 'not arrange': 'Angry', 'not arranging': 'Angry', 'not beg': 'Angry',
         'not begging': 'Angry', 'not begin': 'Angry', 'not beginning': 'Angry', 'not caring': 'Angry',
         'not choose': 'Angry', 'not choosing': 'Angry', 'not claim': 'Angry', 'not claiming': 'Angry',
         'not consent': 'Angry', 'not consenting': 'Angry', 'not continue': 'Angry', 'not continuing': 'Angry',
         'not dare': 'Angry', 'not daring': 'Angry', 'not decide': 'Sad',
         'not deciding': 'Sad', 'not demand': 'Angry', 'not demanding': 'Angry', 'not deserve': 'Angry',
         'not deserving': 'Angry', 'not expect': 'Angry',
         'not expecting': 'Angry', 'not fail': 'Happy', 'not failing': 'Happy', 'not get': 'Sad', 'not getting': 'Sad',
         'not hesitate': 'Sad', 'not hesitating': 'Sad', 'not hurry': 'Happy', 'not hurrying': 'Happy',
         'not intend': 'Sad', 'not intending': 'Sad', 'not learn': 'Angry', 'not learning': 'Angry',
         'not liking': 'Angry', 'not loving': 'Sad', 'not manage': 'Angry',
         'not managing': 'Angry', 'not neglect': 'Sad', 'not neglecting': 'Sad', 'not offer': 'Angry',
         'not offering': 'Angry',
         'not plan': 'Angry', 'not planing': 'Angry', 'not prepare': 'Angry',
         'not preparing': 'Angry', 'not pretend': 'Angry', 'not pretending': 'Angry', 'not proceed': 'Angry',
         'not proceeding': 'Angry',
         'not propose': 'Angry', 'not proposing': 'Sad', 'not refuse': 'Sad', 'not refusing': 'Sad',
         'not start': 'Sad',
         'not starting': 'Sad', 'not stop': 'Happy', 'not stopping': 'Happy', 'not struggle': 'Angry',
         'not struggling': 'Angry',
         'not swear': 'Angry', 'not swearing': 'Angry', 'not threaten': 'Happy', 'not threatening': 'Happy',
         'not try': 'Angry', 'not trying': 'Angry', 'not volunteer': 'Angry',
         'not volunteering': 'Angry', 'not wait': 'Angry', 'not waiting': 'Angry', 'not feel': 'Sad',
         'not feeling': 'Sad', "not able": "Sad", "not do": "Sad"}

    f = re.findall("not\s\w+", text)
    for i in f:
        try:
            text = text.replace(i, d[i])
        except:
            pass
    text = text.lower()
    return text


def removing_contradictions(text):
    if text.count("n't"):
        text = text.replace("n't", " not")
    text = re.sub("ai\snot", "am not", text)
    text = re.sub("wo\snot", "will not", text)
    return text


def emojis_extractor(text):
    emoj = {'Emoji': ['👏 🏾',
 '👏 🏼',
 '👏 🏽',
 '👨 \u200d ❤ ️ \u200d 👨',
 '👩 \u200d ❤ ️ \u200d 👨',
 '👩 \u200d ❤ ️ \u200d 👩',
 '🤤',
 '😘',
 '😋',
 '😛',
 '😝',
 '😜',
 '😂',
 '💪',
 '💪 🏿',
 '💪 🏻',
 '💪 🏾',
 '💪 🏼',
 '💪 🏽',
 '🙏',
 '🙏 🏿',
 '🙏 🏻',
 '🙏 🏾',
 '🙏 🏼',
 '🙏 🏽',
 '🌝',
 '😀',
 '😁',
 '💗',
 '🤝',
 '💟',
 '♥',
 '💘',
 '💝',
 '✔',
 '🌺',
 '🤗',
 '💏',
 '👨 \u200d ❤ ️ \u200d 💋 \u200d 👨',
 '💋',
 '👩 \u200d ❤ ️ \u200d 💋 \u200d 👨',
 '👩 \u200d ❤ ️ \u200d 💋 \u200d 👩',
 '😽',
 '😗',
 '😚',
 '😙',
 '🕺',
 '🕺 🏿',
 '🕺 🏻',
 '🕺 🏾',
 '🕺 🏼',
 '🕺 🏽',
 '💁 \u200d ♂ ️',
 '💁 🏿 \u200d ♂ ️',
 '💁 🏻 \u200d ♂ ️',
 '💁 🏾 \u200d ♂ ️',
 '💁 🏼 \u200d ♂ ️',
 '💁 🏽 \u200d ♂ ️',
 '🤓',
 '👐',
 '👐 🏿',
 '👐 🏻',
 '👐 🏾',
 '👐 🏼',
 '👐 🏽',
 '🙌',
 '🙌 🏿',
 '🙌 🏻',
 '🙌 🏾',
 '🙌 🏼',
 '🙌 🏽',
 '😌',
 '🤣',
 '🤘',
 '🤘 🏿',
 '🤘 🏻',
 '🤘 🏾',
 '🤘 🏼',
 '🤘 🏽',
 '😴',
 '🙂',
 '😇',
 '😍',
 '😃',
 '😆',
 '😅',
 '😄',
 '😊',
 '😎',
 '👍',
 '👍 🏿',
 '👍 🏻',
 '👍 🏾',
 '👍 🏼',
 '👍 🏽',
 '💕',
 '✌',
 '✌ 🏿',
 '✌ 🏻',
 '✌ 🏾',
 '✌ 🏼',
 '✌ 🏽',
 '🖖',
 '🖖 🏿',
 '🖖 🏻',
 '🖖 🏾',
 '🖖 🏼',
 '🖖 🏽',
 '👋',
 '👋 🏿',
 '👋 🏻',
 '👋 🏾',
 '👋 🏼',
 '👋 🏽',
 '😉',
 '💃',
 '💃 🏿',
 '💃 🏻',
 '💃 🏾',
 '💃 🏼',
 '💃 🏽',
 '💛',
 '🤙',
 '🤙 🏿',
 '🤙 🏻',
 '🤙 🏾',
 '🤙 🏼',
 '🤙 🏽',
 '👏',
 '👏 🏿',
 '👏 🏻',
 '💓',
 '😥',
 '😞',
 '😓',
 '🤕',
 '😷',
 '🤒',
 '😶',
 '☹',
 '😦',
 '😭',
 '🤥',
 '😐',
 '😔',
 '😪',
 '🙁',
 '😫',
 '🙃',
 '😩',
 '😟',
 '🤐',
 '💔',
 '😑',
 '😤',
 '🤦 \u200d ♂ ️',
 '🤦 🏿 \u200d ♂ ️',
 '🤦 🏻 \u200d ♂ ️',
 '🤦 🏾 \u200d ♂ ️',
 '🤦 🏼 \u200d ♂ ️',
 '🤦 🏽 \u200d ♂ ️',
 '🙅 \u200d ♂ ️',
 '🙅 🏿 \u200d ♂ ️',
 '🇬 🇱',
 '🙅 🏾 \u200d ♂ ️',
 '🙅 🏼 \u200d ♂ ️',
 '🙅 🏽 \u200d ♂ ️',
 '🤷 \u200d ♂ ️',
 '🤷 🏿 \u200d ♂ ️',
 '🤷 🏻 \u200d ♂ ️',
 '🤷 🏾 \u200d ♂ ️',
 '🖕',
 '🖕 🏿',
 '🖕 🏻',
 '🖕 🏾',
 '🖕 🏼',
 '🖕 🏽',
 '👊',
 '👊 🏿',
 '👊 🏻',
 '👊 🏾',
 '👊 🏼',
 '👊 🏽',
 '😣',
 '🤦',
 '🤦 🏿',
 '🤦 🏻',
 '🤦 🏾',
 '🤦 🏼',
 '🤦 🏽',
 '🤷',
 '🤷 🏿',
 '🤷 🏻',
 '🤷 🏾',
 '🤷 🏼',
 '🤷 🏽',
 '😡',
 '😈',
 '😏',
 '👎',
 '👎 🏿',
 '👎 🏻',
 '👎 🏾',
 '👎 🏼',
 '👎 🏽',
 '😒',
 '🙅 \u200d ♀ ️',
 '🙅 🏿 \u200d ♀ ️',
 '🙅 🏻 \u200d ♀ ️',
 '🙅 🏾 \u200d ♀ ️',
 '🙅 🏼 \u200d ♀ ️',
 '🙅 🏽 \u200d ♀ ️',
 '😠',
 '👿',
 '😵',
 '😱',
 '😮',
 '🙄',
 '😯',
 '🙆 \u200d ♂ ️',
 '🙆 🏿 \u200d ♂ ️',
 '🙆 🏻 \u200d ♂ ️',
 '🙆 🏾 \u200d ♂ ️',
 '🙆 🏼 \u200d ♂ ️',
 '🙆 🏽 \u200d ♂ ️',
 '🙆 \u200d ♀ ️',
 '🙆 🏿 \u200d ♀ ️',
 '🙆 🏻 \u200d ♀ ️',
 '🙆 🏾 \u200d ♀ ️',
 '🙆 🏼 \u200d ♀ ️',
 '🙆 🏽 \u200d ♀ ️',
 '😧',
 '😲',
 '🤞',
 '🤞 🏿',
 '🤞 🏻',
 '🤞 🏾',
 '🤞 🏼',
 '🤞 🏽',
 '😰',
 '😨',
 '😳',
 '😬',
 '🤢',
 '🤧'],
            'Emotion': ['Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Happy',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Sad',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Angry',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Surprise',
 'Fear',
 'Fear',
 'Fear',
 'Fear',
 'Fear',
 'Fear',
 'Fear',
 'Fear',
 'Fear',
 'Fear',
 'Fear',
 'Fear']}
    a = " ".join(c for c in text if c in emoji.EMOJI_DATA).split()
    for i in a:
        try:
            text = text.replace(i, " " + emoj['Emotion'][emoj["Emoji"].index(i)] + " ")
        except:
            pass
    return text.lower()


def cleaning(text):
    text = text.lower()
    text = emojis_extractor(text)
    text = re.sub(r'http\S+|www.\S+', '', text)
    text = removing_contradictions(text)
    text = removing_not(text)
    text = text.split()
    text = removing_shortcuts(text)
    text = ' '.join([i for i in text.split() if not i.isdigit()])
    text = word_tokenize(text)
    words_alpha = removing_stopwords(text)
    words_big = [word for word in words_alpha if len(word) > 2]
    clean_text = lemmatization(words_big)
    clean_text = clean_text.replace('   ', ' ')
    clean_text = clean_text.replace('  ', ' ')
    # print(clean_text)
    return clean_text


def get_emotion(input):
    df = {'Word': ['crushing it', 'relax', 'fresh', 'powerful', 'sick as hell', 'fashionable', 'supported', 'inspiring', 'radiant', 'interesting', 'celebrating', 'compassionate', 'plenty', 'dominating', 'fantastic', "heckin' awesome", 'excellent', 'stylish', 'chill', 'spellbinding', 'glad', 'gorgeous', 'hip', 'empowering', 'secure', 'festive', 'knowledgeable', 'classy', 'ridiculously awesome', 'having a good time', 'incredible', 'cheering', 'content', 'punctual', 'exhilarated', 'got this', 'charming', 'fun', 'eased', 'heck yeah', 'joyful', 'sweet', 'passionate', 'over the moon', 'chill', 'gnarly', 'festive', 'appreciative', 'spectacular', 'healthy', 'refreshed', 'inspire', 'glowing', 'having a great time', 'optimistic', 'resilient', 'positive', 'engaged', 'alive', 'luscious', 'feeling good', 'cared for', 'getting after it', 'energized', 'enlightening', 'smiling ear to ear', 'slaying it', 'thankful', 'safe', 'party', 'excited', 'pretty', 'creative', 'pleasure', 'seductive', 'super', 'boss', 'confident', 'comfort', 'gorgeous', 'grateful', 'fly', 'impressive', 'upbeat', 'mad hype', 'cute', 'attentive', 'considerate', "freakin' awesome", 'nice', 'like', 'valued', 'amused', 'epic', 'motivated', 'doing it big', 'outstanding', 'zealous', 'pleased', 'marvelous', 'accomplished', 'happy', 'rad', 'fulfilled', 'like', 'developed', 'charming', 'laughing', 'flowing', 'tranquil', 'optimistic', 'ardent', 'enticing', 'happy', 'respectful', 'stunning', 'fervent', 'exquisite', 'tickled', 'mega', 'honest', 'slay', 'improved', 'fire', 'tolerant', 'relieved', 'radical', 'enriching', 'credible', 'uplifted', 'carefree', 'fulfilled', 'rejuvenated', 'superb', 'radiating', 'professional', 'wonderful', 'friendly', 'soothed', 'mesmerizing', 'inviting', 'make up', 'dedicated', 'fabulous', 'amped', 'blessed', 'firing', 'way too cool', 'enchanting', 'soothing', 'smiling', 'peaceful', 'authentic', 'eager', 'terrific', 'persevering', 'feeling great', 'scrumptious', 'got it', 'phenomenal', 'effusive', 'yass', 'haven', 'gushing', 'challenged', 'satisfied', 'overjoyed', 'killer', 'wise', 'handsome', 'stimulated', 'thoughtful', 'digging it', 'hopeful', 'beautiful', 'elegant', 'astonished', 'well-structured', 'laughing', 'swag', 'loved', 'peaceful', 'mouth-watering', 'fire', 'nurturing', 'kicking it', 'fierce', 'sick-nasty', 'jazzed', 'elated', 'revitalized', 'compelling', 'loving life', "ballin'", 'turnt up', 'neat-o', 'soothe', 'reliable', 'zoned in', 'yummy', 'appealing', 'cheerful', 'good', 'excellent', 'sensational', 'open-minded', 'accepting', 'buzzed', 'pumped', 'proud', 'diverse', 'connected', 'sweeeet', 'ecstatic', 'mellow', 'outstanding', 'rejuvenated', 'easy', 'patient', 'blessed', 'exciting', 'intelligent', 'breathtaking', 'cool', 'versatile', 'breathtaking', 'thriving', 'engaging', 'well-planned', 'effective', 'living the dream', 'motivating', 'potent', 'satisfied', 'smashing it', 'lucky', 'rad', 'alluring', 'lovely', 'stimulating', 'stoked', 'incredible', 'balanced', 'fulfilling', 'amazing', 'heartwarming', 'gleeful', 'intense', 'appreciative', 'gnarly', 'hype af', 'genuine', 'mesmerizing', 'merry', 'empathetic', 'having a blast', 'perfect', 'empowered', 'helpful', 'juiced', 'welcoming', 'fiery', 'blissful', 'way too sick', 'encouraged', 'dope', 'equitable', 'delicious', 'relief', 'bursting', 'enjoyable', 'amazing', 'successful', 'totally crushing it', 'elated', 'tight', 'efficient', 'friendship', 'lit', 'cheering', 'care', 'persuasive', 'groovy', 'totally killing it', 'world-class', 'fit in', 'satisfying', 'love', 'evolved', 'hell yeah', 'understanding', 'inspired', 'uplifting', 'trendy', 'splendid', 'celebrating', 'curious', 'committed', 'enthusiastic', 'phenomenal', 'vibrant', 'attractive', 'zero complaints', 'pumping', 'basking in the glow', 'tranquil', 'serene', 'comfortable', 'entertained', 'jubilant', 'awesome', 'great', 'wonderful', 'legendary', 'fascinating', 'sparking', 'living it up', 'comforted', 'grinning from ear to ear', 'overjoyed', 'giddy', 'cooperative', 'restored', 'serene', 'grateful', 'joyful', 'enthralling', 'tubular', 'too legit to quit', 'psyched', 'great', 'dope', 'living large', 'lovely', 'team-oriented', 'stimulated', 'euphoric', 'kind', 'utopia', 'hopeful', 'adaptable', 'distinguished', 'captivating', 'convincing', 'collaborative', 'feeling lucky', 'gratified', 'enlivened', 'delighted', 'winning', 'glad', 'beautiful', 'fair', 'hyped', 'organized', 'effervescent', 'thrilled', 'radiant', 'belonged', 'lit', 'killing it', 'enthusiastic', 'relaxed', 'calm', 'flexible', 'enough','hella dope', 'tasty', 'jolly', 'caring', 'encouraging', 'owning it', 'dependable', 'fulfill', 'stoked out of my mind', 'inclusive', 'delightful', 'glowing', 'cheerful', 'balance', 'gratifying', 'sophisticated', 'transparent', 'content', 'refreshed', 'cool', 'vibrant', 'relieved', 'renewed', 'dynamic', 'spellbinding', 'thrilling', 'timely', 'responsive', 'recommendfantastic', 'flavorful', 'out of sight', 'fascinated', 'rewarding', 'delightful', 'lit af', 'best', 'glamorous', 'motivated', 'charmed', 'far out', 'opportunity', 'enchanting', 'on cloud nine', 'energizing', 'truthful', 'thrilled', 'captivating', 'lively', 'pleasant', 'transformed', 'wow', 'superb', 'terrific', 'wow', 'calm', 'blissful', 'centered', 'savory', 'courteous', 'smiling', 'innovative', 'ecstatic', 'sensual', 'blissed-out', 'rousing', 'adorable', 'perfect', 'happy-go-lucky', 'accessible', 'fortunate', 'delectable', 'productive', 'crushing', 'irresistible', 'euphoric', 'supportive', 'walking on sunshine', 'pleased as punch', 'open', 'totally owning it', 'best', 'awesome', 'trustworthy', 'explorative', 'attractive', 'bothered', 'chagrined', 'aggression', 'harsh', 'put out', 'teed off', 'aggravated', 'cancel', 'disgusted', 'insulting to', 'sexist', 'misogyny', 'appalled', 'toxic', 'rankled', 'issue', 'yawning', 'agitated', 'offended', 'unimpressed', 'misunderstood', 'fuming', 'malicious', 'deficient', 'done with', 'difficult', 'the last straw', 'sassy', 'spiteful', 'enough already', 'irascible', 'cringe', 'sexism', 'provoked', 'livid', 'discontent', 'offensive', 'wtf', 'quarrelsome', 'disenchanted', 'irate', 'disturbed', 'contentious', 'had it up to here', 'screwed over', 'bored to tears', 'horrible', 'let down', 'wroth', 'ill-mannered', 'testy', 'dissatisfied', 'combative', 'touchy', 'bitterness', 'worn out', 'indignant', 'shitty', 'ill-natured', 'hostility', 'rant', 'rancid', 'petty', 'insulted by', 'mess', 'hate', 'insane', 'humiliated', 'at the end of my rope', 'wrung out', 'domineering', 'outrageous', 'sore at', 'crazy', 'wounded', 'irritated beyond belief', 'protest', 'envious', 'risky', 'hatred', 'bullying', 'cross', 'hot under the collar', 'done', 'bs', 'violence', 'revulsion', 'letdown', 'critical', 'dismayed', 'humiliating', 'up to here', 'riot', 'demeaned', 'hateful', 'aggressive', 'impatient', 'disillusioned', 'petulant', 'perturbed', 'bored out of my mind', 'struggle', 'ignorant', 'bored to death', 'bored out of my skull', 'sick of it', 'smart-alecky', 'homophobic', 'violent', 'swear', 'hotheaded', 'audacity', 'fucked up', 'mad', 'bored silly', 'disgruntled', 'overbearing', 'exasperated', 'hard to please', 'belligerent', 'insulted', 'disgust', 'hacked off', 'crabby', 'guilt', 'hysterical', 'furious', 'intimidate', 'repulsed', 'discourteous', 'sick and tired', 'riled', 'annoyed', 'disorganized', 'bitter', 'shameful', 'peeved', 'insolent', 'chaotic', 'abominate', 'frustrated', 'not happy', 'snide', 'threatening', 'worked up', 'transphobia', 'overpoweringsick and tired', 'tetchy', 'nasty', 'homophobia', 'mean-spirited', 'embarrassing', 'hostile', 'pugnacious', 'repulsive', 'abhorrent', 'uncivil', 'close-minded', 'useless', 'passive aggressive', 'infuriated', 'demeaning', 'disgusting', 'impertinent', 'vexed', 'bad-tempered', 'repugnant', 'scream', 'snippy', 'cantankerous', 'mortified', 'troublesome', 'scandal', 'brassy', 'disgruntledproblem', 'irritated', 'pissed off', 'over it', 'vindictive', 'abomination', 'exhausted', 'insulting', 'yawn', 'resentment', 'marginalized', 'ashaming', 'rude', 'grumpy', 'fed up to here', 'embarass', 'out of sorts', 'crusty', 'surly', 'resentful', 'intimidating', 'bummed out', 'jealous', 'angry', 'quick-tempered', 'malevolent', 'disrespectful', 'ill-tempered', 'fed up', 'soured', 'chaos', 'sore', 'chafed', 'ugh', 'steaming', 'argumentative', 'ornery', 'ticked off', 'splenetic', 'shame', 'racism', 'crotchety', 'bullshit', 'insult', 'snappy', 'miffed', 'huffy', 'roiled', 'short-tempered', 'worn down', 'dangerous', 'repulsion', 'bellicose', 'cheeky', 'piqued', 'gruff', 'seething', 'toxic competition', 'screwed', 'pissed', 'jaded', 'irked', 'saucy', 'temperamental', 'racist', 'curmudgeonly', 'outraged', 'enraged', 'gross', 'incensed', 'tired of it all', 'uninterested', 'yawned', 'unnecessary', 'wrathful', 'unruly', 'irked to death', 'yawny', 'peevish', 'displeased', 'confrontational', 'embarrassed', 'concern', 'impolite', 'lonesome', 'injured', 'demoralized', 'stress', 'defeated', 'miserable', 'sorry', 'icky', 'jumpy', 'sigh', 'vulnerable', 'subpar', 'crestfallen', 'ignored', 'despondent', 'traumatized', 'left out', 'lack', 'timid', 'abused', 'exploited', 'dying', 'confused', 'burdened', 'jittery', 'low', 'unsavory', 'dropped out', 'vile', 'nervous', 'lie', 'choked up', 'inferior', 'despairing', 'dislike', 'tedious', 'deprived', 'discarded', 'guilty', 'regretful', 'dire', 'black', 'anguished', 'down', 'panic', 'tense', 'oppose', 'remorseful', 'trauma', 'disfavor', 'disconnected', 'perplexed', 'fake', 'stressed out', 'blues', 'upset', 'disappointing', 'wistful', 'tearful', 'grief-stricken', 'hopeless', 'woebegone', 'fatigue', 'overwhelmed', 'disheartening', 'shoddy', 'defective', 'worry', 'paranoid', 'unstable', 'lousy', 'meh', 'inconsolable', 'cry', 'broken', 'regrettable', 'indecipherable', 'sick', 'discontented', 'unlucky', 'guarded', 'blue', 'helpless', 'incomprehensible', 'trembling', 'downtrodden', 'quiet', 'mournful', 'low-spirited', 'wrong', 'shaky', 'dull', 'lugubrious', 'stressed', 'desolation', 'apologize', 'petrified', 'unsatisfied', 'teary-eyed', 'disheartened', 'bored', 'betrayed', 'profound', 'inexcusable', 'uncheerful', 'abysmal', 'insipid', 'burnt out', 'skeptical', 'heart-rending', 'sunk-in', 'crushed', 'painful', 'mourning', 'powerless', 'discourage', 'atrocious', 'spurn', 'scared', 'weepy', 'alone', 'threatened', 'drained', 'torture', 'bleak', 'victimized', 'repentant', 'worried', 'anxious', 'sappy', 'preoccupied', 'whimpering', 'opaque', 'insecure', 'anguish', 'abandoned', 'torn', 'dispirited', 'glum', 'off-putting', 'zapped', 'unacceptable', 'forsaken', 'pessimistic', 'dismal', 'crying', 'distressed', 'tragic', 'excluded', 'disappointed', 'nerve', 'alienated', 'suspicious', 'bad', 'lonely', 'lackluster', 'failure', 'regret', 'worse', 'uncomfortable', 'sickened', 'stifled', 'disconsolate', 'self-conscious', 'gloomy', 'pain', 'depressed', 'unfortunate', 'heartbroken', 'reject', 'moody', 'inaccessible', 'fatigued', 'bewildered', 'morose', 'desolate', 'scorn', 'deflated', 'panicked', 'uneasy', 'despair', 'boring', 'fomo', 'unclear', 'weary', 'uncaring', 'unfavorable', 'puzzled', 'murky', 'distraught', 'raw', 'not diverse', 'apathetic', 'sullen', 'hard', 'vague', 'unresponsive', 'saddened', 'wary', 'dead', "doesn't care", 'doubtful', 'crappy', 'joyless', 'imposter syndrome', 'wronged', 'oppressed', 'awful', 'funereal', 'long', 'morbid', 'brokenhearted', 'restless', 'aggrieved', 'deserted', 'overlooked', 'discouraging', 'pathetic', 'gloom', 'afraid', 'dread', 'bore', 'misery', 'mundane', 'emptiness', 'dejected', 'subdued', 'downcast', 'lost', 'lame', 'abhor', 'unhappy', 'sad', 'unpleasant', 'ache', 'wretched', 'terrible', 'unmotivated', 'worn-out', 'suffocated', 'trapped', 'disengaged', 'sorrowful', 'agony', 'dreadful', 'overwhelm', 'unsafe', 'numb', 'suffering', 'complacent', 'rage', 'exhaust', 'unbearable', 'zoned-out', 'grim', 'breakdown', 'disdain', 'grief', 'spent', 'anxiety', 'drop out', 'isolated', 'damn', 'detest', 'unsure', 'burned out', 'cheated', 'tired', 'clique', 'bummed', 'pensive', 'ashamed', 'shattered', 'queasy', 'self-pity', 'inadequate', 'cliquey', 'indecisive', 'fear', 'forlorn', 'oppressive', 'brutal', 'wasted', 'poor', 'depressing', 'downhearted', 'hurt', 'doleful', 'desperate', 'pitiable', 'stricken', 'misty', 'unrelenting', 'substandard', 'unloved', 'cheerless', 'loathe', 'repugn', 'dark', 'ambiguous', 'cynical', 'woeful', 'indifferent', 'disapprove', 'sepulchral', 'suppressed', 'dreary', 'rejected', 'unsatisfactory', 'mistreated', 'disagreeable', 'lifeless', 'pressed', 'despise', 'melancholic', 'crummy', 'devastated', 'empty', 'foggy', 'neglected', 'pitiful', 'melancholy', 'sunk', 'uncertain', 'heart-wrenching', 'yucky', 'heavy-hearted', 'troubled', 'displeasing', 'somber', 'loveless', 'tormented', 'baffled', 'bereaved', 'muddled', 'sorrow', 'unappreciated', 'terrified', 'unwanted', 'heavyhearted', 'fearful'], 'Emotion':['Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Sad', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry', 'Angry']}
    text = cleaning(input).split()
    emotion_values = []
    emotions = {"Happy": 0, "Angry": 0, "Sad": 0, "Neutral": 0}
    y = 0
    try:
        for i in text:
            try:
                a = df['Word'].index(i)
                if a:
                    emotions[df['Emotion'][a]] += 1
                else:
                    emotions["Neutral"] += 1
            except:
                pass
        if sum(emotions.values()) is 0:
            return emotions
        for i in emotions:
            emotion_values.append(round((emotions[i] / sum(emotions.values())), 2))
        for j in emotions:
            emotions[j] = emotion_values[y]
            y += 1
        return emotions
    except:
        pass